prog:background.o main.o fonction.o hero.o enigmealeatoire.o enigmealf.o enigmestat.o jeux.o ennemi.o functions.o
	gcc  background.o main.o fonction.o hero.o enigmealeatoire.o enigmealf.o enigmestat.o jeux.o ennemi.o functions.o -o prog -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
main.o:main.c	
	gcc -c main.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
background.o:background.c
	gcc -c background.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
fonction.o:fonction.c
	gcc -c fonction.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
hero.o:hero.c
	gcc -c hero.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g	
enigmealeatoire.o:enigmealeatoire.c
	gcc -c enigmealeatoire.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
enigmealf.o:enigmealf.c
	gcc -c enigmealf.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g	
enigmestat.o:enigmestat.c
	gcc -c enigmestat.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
jeux.o:jeux.c
	gcc -c jeux.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
ennemi.o:ennemi.c	
	gcc -c ennemi.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
functions.o:functions.c	
	gcc -c functions.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
